### ISSUE TITLE
60% adoption is the threshold for contact tracing to work. What research is this estimate part of?

### ISSUE THREAD

**Issue by ghost** [BDI-pathogens/covid-19_instant_tracing#5]
Hi @MichelleKendall , I read in [WIRED](https://www.wired.co.uk/article/uk-coronavirus-spread-app-phone-data) that:

> "[the] Big Data Institute estimates that over 60 per cent of the UK’s population would have to be using the app for digital contact tracing to reach enough people as they become infected."

What research is this estimate part of?

**Comment by MichelleKendall** [comment]
Hi,

My apologies for the delay in responding. The original versions of the relevant reports are here in this repository but perhaps the more convenient / informative places to read them are on our [website](http://coronavirus-fraser-group.org/) and in our [Science paper](https://doi.org/10.1126/science.abb6936).

Thanks,

Michelle

**Comment by ghost** [comment]
Thank you, @MichelleKendall .
